### ISSUE TITLE
Debug logging?

### ISSUE THREAD

**Issue by ianneub** [juitde/traefik-plugin-fail2ban#1]
Hello @dkreuer !

First off I wanted to let you know this project is exactly what I was looking for. A way to implement Fail2Ban in Traefik based on Unauthorized access. Thank you!

I tried setting the logLevel setting to `DEBUG` but didn't see any output. I also didn't see any output with `INFO`.

```yaml
middlewares:
  fail2ban:
    plugin:
      fail2ban:
        logLevel: DEBUG
```

```yaml
experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/juitde/traefik-plugin-fail2ban"
      version: "v0.1.0"
```

Maybe I've got it configured wrong? What kind of output should we expect to see?

I'm using this in a Docker container if that might impact things.

Thank you!
